# Generated by Django 5.2.1 on 2025-06-25 15:13

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HoughPreviewFile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('plan_upload_file_id', models.UUIDField()),
                ('user_mask_upload_file_id', models.UUIDField()),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('file_path', models.CharField(max_length=255)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hough_previews', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Hough preview файл',
                'verbose_name_plural': 'Hough preview файлы',
                'ordering': ['-created_at'],
            },
        ),
    ]
