# Generated by Django 5.2.1 on 2025-06-25 16:36

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0002_houghpreviewfile'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reconstruction',
            fields=[
                ('id', models.AutoField(primary_key=True, serialize=False)),
                ('mesh_file_path', models.CharField(max_length=255)),
                ('created_at', models.DateTimeField(default=django.utils.timezone.now)),
                ('is_saved', models.BooleanField(default=False)),
                ('saved_at', models.DateTimeField(blank=True, default=None, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reconstructions', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': '3D реконструкция',
                'verbose_name_plural': '3D реконструкции',
                'ordering': ['-created_at'],
            },
        ),
    ]
