# Generated by Django 5.2.1 on 2025-06-26 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0003_reconstruction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconstruction',
            name='is_saved',
        ),
        migrations.AddField(
            model_name='reconstruction',
            name='name',
            field=models.CharField(blank=True, default=None, max_length=255, null=True),
        ),
    ]
