# Generated by Django 5.2.1 on 2025-06-26 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0004_remove_reconstruction_is_saved_reconstruction_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='reconstruction',
            name='saved_at',
            field=models.DateTimeField(blank=True, db_index=True, default=None, null=True),
        ),
    ]
