# Generated by Django 5.2.1 on 2025-06-30 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0005_alter_reconstruction_saved_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconstruction',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В очереди'), (2, 'В обработке'), (3, 'Готово'), (4, 'Ошибка')], default=1),
        ),
        migrations.AlterField(
            model_name='reconstruction',
            name='mesh_file_path',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
