# Generated by Django 5.2.1 on 2025-06-30 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0006_reconstruction_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='reconstruction',
            name='plan_signs',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
