# Generated by Django 5.2.1 on 2025-07-01 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('reconstruction', '0008_reconstruction_rooms'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='reconstruction',
            name='plan_signs',
        ),
    ]
