services:
  3d-backend:
    build:
      context: ./backend
      target: app
    image: 3d-backend
    container_name: 3d-backend
    restart: unless-stopped
    env_file: .env
    hostname: backend.3d.internal
    networks:
      - 3d
      - postgres
    volumes:
      - 3d-media:/app/core/media
  3d-static:
    build:
      context: ./backend
      target: static
    image: 3d-static
    container_name: 3d-static
    restart: unless-stopped
    hostname: static.3d.internal
    networks:
      - 3d
    volumes:
      - ./logs/3d-static:/var/log/nginx/
  3d-nginx:
    build: nginx
    image: 3d-nginx
    container_name: 3d-nginx
    restart: unless-stopped
    hostname: nginx.3d.internal
    networks:
      - 3d
    ports:
      - 127.0.0.1:9070:80
    volumes:
      - ./logs/3d-nginx:/var/log/nginx/

volumes:
  3d-media:
    name: 3d-media

networks:
  3d:
    name: 3d
    driver: bridge
  postgres:
    external: true
