# Generated by Django 5.2.1 on 2025-06-25 14:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('upload_files', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uploadedfile',
            name='source_type',
            field=models.PositiveSmallIntegerField(choices=[(1, '2D-план'), (2, 'Окружение пользователя'), (3, 'Маска пользователя')]),
        ),
    ]
