# Generated by Django 5.2.1 on 2025-06-23 14:36

import django.utils.timezone
import mainpage.models
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ApplicationFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('os', models.CharField(choices=[('android', 'Android')], default='android', max_length=20, verbose_name='ОС')),
                ('version', models.CharField(max_length=20, verbose_name='Версия')),
                ('file', models.FileField(upload_to=mainpage.models.app_upload_to, verbose_name='Файл')),
                ('uploaded_at', models.DateTimeField(db_index=True, default=django.utils.timezone.now, verbose_name='Загружено')),
                ('hidden', models.BooleanField(default=False, verbose_name='Скрыто')),
            ],
            options={
                'verbose_name': 'Файл приложения',
                'verbose_name_plural': 'Файлы приложения',
                'ordering': ['-uploaded_at'],
            },
        ),
    ]
