# Generated by Django 5.2.1 on 2025-07-01 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='identification',
            name='state',
        ),
        migrations.AddField(
            model_name='identification',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'В очереди'), (2, 'В обработке'), (3, 'Готово'), (4, 'Ошибка'), (5, 'Не найдено')], default=1),
        ),
    ]
