# Generated by Django 5.2.1 on 2025-07-01 17:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('identification', '0002_remove_identification_state_identification_status'),
        ('reconstruction', '0009_remove_reconstruction_plan_signs'),
    ]

    operations = [
        migrations.AddField(
            model_name='identification',
            name='reconstruction',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='identifications', to='reconstruction.reconstruction'),
        ),
    ]
